version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - 3307:80
    links:
      - db:db
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "5647:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_DEBUG_LOG: 'true'
    volumes:
      - ./:/var/www/html/wp-content/themes/gct
      - ./.plugins:/var/www/html/wp-content/plugins
      - ./.uploads:/var/www/html/wp-content/uploads
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
  db_data:
